version: "2"
run:
  timeout: 5m

formatters:
  enable:
    - goimports # checks if the code and import statements are formatted according to the 'goimports' command
    - gofmt # checks if the code is formatted according to the 'gofmt' command
    #- golines # checks if code is formatted, and fixes long lines

  settings:
    golines:
      max-len: 150

linters:
  default: none
  enable:
    # go vet is excellent and finds suspicious constructs and potential bugs
    - govet
    # staticcheck is a powerful linter that catches bugs, performance issues, and style problems
    - staticcheck
    # errcheck ensures all error return values are handled
    # - errcheck
    # ineffassign detects variables assigned but never used
    - ineffassign
    # unused detects unused variables, constants, functions, etc.
    - unused
    # gosec is a security checker
    # - gosec
    # revive is a more opinionated, customizable alternative to golint
    # - revive
    # whitespace enforces consistent spacing and alignment
    - whitespace
  disable:
    - errcheck

  settings:
    govet:
      enable:
      - shadow
#   gocyclo:
#     min-complexity: 15
#
#   dupl:
#     threshold: 100
#   goconst:
#     min-len: 3
#     min-occurrences: 3
#   misspell:
#     locale: US
#   lll:
#     line-length: 120
#   goimports:
#     local-prefixes: github.com/xphyr/synology-csi
#   revive:
#     severity: warning
#     confidence: 0.8
#     rules:
#       - name: exported
#       - name: blank-imports
#       - name: context-as-argument
#       - name: context-keys-type
#       - name: dot-imports
#       - name: error-return
#       - name: error-strings
#       - name: error-naming
#       - name: if-return
#       - name: increment-decrement
#       - name: var-naming
#       - name: var-declaration
#       - name: package-comments
#       - name: range
#       - name: receiver-naming
#       - name: time-naming
#       - name: unexported-return
#       - name: indent-error-flow
#       - name: errorf
#       - name: empty-block
#       - name: superfluous-else
#       - name: unreachable-code
#       - name: redefines-builtin-id