version: "2"
run:
  timeout: 5m

formatters:
  enable:
    - goimports # checks if the code and import statements are formatted according to the 'goimports' command
    - gofmt # checks if the code is formatted according to the 'gofmt' command

# The following linters are aspirational. I have enabled a bunch and the ones that are commented out still have multiple warnings that need to be addressed.
linters:
  default: none
  enable:
    # go vet is excellent and finds suspicious constructs and potential bugs
    - govet
    # staticcheck is a powerful linter that catches bugs, performance issues, and style problems
    - staticcheck
    # errcheck ensures all error return values are handled
    # - errcheck
    # ineffassign detects variables assigned but never used
    - ineffassign
    # unused detects unused variables, constants, functions, etc.
    - unused
    # gosec is a security checker
    # - gosec
    # revive is a more opinionated, customizable alternative to golint
    - whitespace
    # misspell checks for misspelled words
    - misspell
    # dupl checks for duplicated code
    - dupl
    # bidichk checks for bidirectional Unicode characters
    - bidichk
    # gocritic checks for code quality issues
    # - gocritic
    # govet checks for suspicious constructs and potential bugs
    - govet
    # modernize checks for modern Go language features
    # - modernize
    
  disable:
    - errcheck

  settings:
    govet:
      enable:
      - shadow
    dupl:
      threshold: 150
