---
clients:
  - host: 192.168.1.1
    port: 5000
    https: false
    username: username
    password: password
  - host: 172.16.20.13
    port: 5000
    https: false
    username: username
    password: password
    clientsubnetoverride: "172.16.20.0/24"

#host:                      # ipv4 address or domain of the DSM
#port:                      # port for connecting to the DSM
#https:                     # set this true to use https. you need to specify the port to DSM HTTPS port as well
#username:                  # username
#password:                  # password
#clientsubnetoverride       # subnet in CIDR notation to allow for secondary storage networks - optional